// Test 4 — scripted asset-generation harness (D-RA-24, first Claude-in-the-loop
// dogfood). Drives the LIVE Limner CMA agent through the core task — "from this
// source photo, produce a Beaux-Arts oil-painting portrait" — across each
// pipeline, plus a format-advice turn that exercises the file-types skill.
//
// This is the first real proof the tool schemas pass the Messages API (a masked
// model_request_failed_error is the headline failure mode) and that the agent
// reaches the prod MCP tools via the vault OAuth path.
//
// STAGED SPEND. DEFAULT = dry-validate: resolve + validate config and the source
// image, build the task plan and user-message shapes, print them, exit 0 — no
// network, no credentials, no agent call. LIVE (--execute, requires
// ANTHROPIC_API_KEY): runs the selected stage's sessions against the live agent.
//   --stage 1  (default) free: Midjourney portrait (prompt-only) + format advice.
//   --stage 2  PAID: DALL·E + Recraft renditions (+ optional --include-compose).
// Stage 2 bills DALL·E / Recraft / agent inference — run only on explicit go.
//
// Secrets: ANTHROPIC_API_KEY from the environment only — never printed, never
// written. Account IDs (agent / vault / environment) and the --source-image path
// come from flags/env, never hardcoded. Outputs go to a gitignored test-runs/
// dir; the source photo and generated bytes never enter the JSON artifacts.
//
// Run via: pnpm --filter @limner/limner-agent test-agent -- [flags]
//          (node dist/test-agent.js [flags])
//
// Limner is an independent third-party project on Anthropic's CMA platform; this
// script *uses* the CMA API. It is not an Anthropic or Claude product.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Buffer } from 'node:buffer';
import process from 'node:process';

import {
  COMPOSE_TASK,
  STAGE1_TASKS,
  STAGE2_TASKS,
  buildUserMessageContent,
  evaluateTask,
  normalizeToolName,
  reduceEvents,
  summarizeAssetForArtifact,
  type TaskResult,
  type TaskSpec,
  type TaskTranscript,
} from './test-harness.js';

const here = dirname(fileURLToPath(import.meta.url));
// From dist/test-agent.js up to the repo root (../../..) for the default outputs dir.
const REPO_ROOT = resolve(here, '../../..');

interface Cli {
  execute: boolean;
  stage: 1 | 2;
  agentId?: string;
  vaultId?: string;
  environmentId?: string;
  sourceImage?: string;
  includeCompose: boolean;
  outDir?: string;
  maxToolCalls: number;
  taskTimeoutMs: number;
}

function parseArgs(argv: readonly string[]): Cli {
  const cli: Cli = {
    execute: false,
    stage: 1,
    includeCompose: false,
    maxToolCalls: 8,
    taskTimeoutMs: 240_000,
  };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--execute') cli.execute = true;
    else if (arg === '--stage') cli.stage = argv[++i] === '2' ? 2 : 1;
    else if (arg === '--agent-id') cli.agentId = argv[++i];
    else if (arg === '--vault-id') cli.vaultId = argv[++i];
    else if (arg === '--environment-id') cli.environmentId = argv[++i];
    else if (arg === '--source-image') cli.sourceImage = argv[++i];
    else if (arg === '--include-compose') cli.includeCompose = true;
    else if (arg === '--out') cli.outDir = argv[++i];
    else if (arg === '--max-tool-calls') cli.maxToolCalls = Number(argv[++i]) || cli.maxToolCalls;
    else if (arg === '--task-timeout-ms') cli.taskTimeoutMs = Number(argv[++i]) || cli.taskTimeoutMs;
  }
  cli.agentId ??= process.env.LIMNER_AGENT_ID;
  cli.vaultId ??= process.env.LIMNER_VAULT_ID;
  cli.environmentId ??= process.env.LIMNER_ENV_ID;
  cli.sourceImage ??= process.env.LIMNER_SOURCE_IMAGE;
  return cli;
}

const MEDIA_BY_EXT: Record<string, string> = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
};

function mediaTypeForPath(path: string): string {
  const mt = MEDIA_BY_EXT[extname(path).toLowerCase()];
  if (!mt) {
    throw new Error(
      `unrecognized source-image extension on ${path} (expected .jpg/.jpeg/.png/.webp/.gif)`,
    );
  }
  return mt;
}

function selectTasks(cli: Cli): TaskSpec[] {
  if (cli.stage === 1) return [...STAGE1_TASKS];
  const tasks = [...STAGE2_TASKS];
  if (cli.includeCompose) tasks.push(COMPOSE_TASK);
  return tasks;
}

function timestamp(): string {
  return new Date().toISOString().replace(/[:.]/g, '-');
}

function shortToolName(name: string): string {
  return name.replace(/^limner_generate_/, '').replace(/^limner_/, '');
}

// ---------------- dry-validate (default) ----------------

function dryValidate(cli: Cli): void {
  const tasks = selectTasks(cli);
  let sourceImageInfo: { path: string; mediaType: string; bytes: number } | undefined;
  if (cli.sourceImage) {
    const bytes = readFileSync(cli.sourceImage).length; // validate readable; content never printed
    sourceImageInfo = { path: cli.sourceImage, mediaType: mediaTypeForPath(cli.sourceImage), bytes };
  }
  const needsImage = tasks.some((t) => t.attachImage);

  const preview = {
    mode: 'dry-validate',
    stage: cli.stage,
    note: 'no API calls, no credentials, no agent invocation',
    config: {
      agentId: cli.agentId ?? '<missing — set --agent-id or LIMNER_AGENT_ID>',
      vaultId: cli.vaultId ?? '<missing — set --vault-id or LIMNER_VAULT_ID>',
      environmentId: cli.environmentId ?? '<none — a cloud environment will be created at run time>',
      sourceImage: sourceImageInfo ?? (needsImage ? '<missing — required by image tasks at run time>' : 'n/a'),
      apiKey: process.env.ANTHROPIC_API_KEY ? 'present in env' : 'ABSENT (required for --execute)',
    },
    tasks: tasks.map((t) => ({
      id: t.id,
      stage: t.stage,
      kind: t.kind,
      expectedTool: t.expectedTool,
      attachImage: t.attachImage,
      promptChars: t.prompt.length,
      userMessageBlocks: buildUserMessageContent(
        t.prompt,
        t.attachImage && sourceImageInfo
          ? { data: '<omitted>', mediaType: sourceImageInfo.mediaType }
          : undefined,
      ).map((b) => (b.type === 'image' ? `image(${b.source.media_type})` : `text(${b.text.length} chars)`)),
    })),
  };
  process.stdout.write(`${JSON.stringify(preview, null, 2)}\n`);
  process.stdout.write(
    '\ntest-agent: dry-validate only — no API calls made. ' +
      'Re-run with --execute (and ANTHROPIC_API_KEY set) to run the live session(s).\n',
  );
}

// ---------------- live run (--execute) ----------------

interface TaskRunResult {
  taskId: string;
  sessionId: string;
  consoleUrl: string;
  capped: boolean;
  timedOut: boolean;
  result: TaskResult;
  derivedPrompt?: string;
  finalTextPreview: string;
  savedAssets: string[];
  error?: string;
}

function preview(text: string, max = 600): string {
  const oneLine = text.replace(/\s+/g, ' ').trim();
  return oneLine.length > max ? `${oneLine.slice(0, max)}…` : oneLine;
}

async function main(): Promise<void> {
  const cli = parseArgs(process.argv.slice(2));

  if (!cli.execute) {
    dryValidate(cli);
    return;
  }

  // ---- LIVE ----
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('test-agent --execute requires ANTHROPIC_API_KEY in the environment');
  if (!cli.agentId) throw new Error('missing --agent-id (or LIMNER_AGENT_ID)');
  if (!cli.vaultId) throw new Error('missing --vault-id (or LIMNER_VAULT_ID)');

  const tasks = selectTasks(cli);
  const needsImage = tasks.some((t) => t.attachImage);
  let image: { data: string; mediaType: string } | undefined;
  if (needsImage) {
    if (!cli.sourceImage) throw new Error('image tasks need --source-image (or LIMNER_SOURCE_IMAGE)');
    const bytes = readFileSync(cli.sourceImage);
    image = { data: bytes.toString('base64'), mediaType: mediaTypeForPath(cli.sourceImage) };
  }

  const outDir = cli.outDir ?? resolve(REPO_ROOT, 'test-runs', timestamp());
  mkdirSync(outDir, { recursive: true });

  // SDK loaded only on the live path so dry-validate needs neither it nor a key.
  const { default: Anthropic } = await import('@anthropic-ai/sdk');
  const client = new Anthropic({ apiKey });

  // Environment: reuse if given, else create a cloud container with open egress.
  let environmentId = cli.environmentId;
  if (!environmentId) {
    const env = await client.beta.environments.create({
      name: `limner-test4-${timestamp()}`,
      config: { type: 'cloud', networking: { type: 'unrestricted' } },
    });
    environmentId = env.id;
    process.stdout.write(`Created environment ${environmentId} (reuse with --environment-id)\n`);
  }

  process.stdout.write(
    `\nTest 4 — stage ${cli.stage} — ${tasks.length} task(s)\n` +
      `agent ${cli.agentId} · vault ${cli.vaultId} · env ${environmentId}\n` +
      `outputs → ${outDir}\n\n`,
  );

  const runResults: TaskRunResult[] = [];
  for (const task of tasks) {
    process.stdout.write(`▶ ${task.id} (${task.expectedTool ?? task.kind})\n`);
    try {
      const session = await client.beta.sessions.create({
        agent: cli.agentId,
        environment_id: environmentId,
        vault_ids: [cli.vaultId],
        title: `Limner Test 4 — ${task.id}`,
        metadata: { test: 'test4', task: task.id, stage: String(task.stage) },
      });
      const consoleUrl = `https://platform.claude.com/workspaces/default/sessions/${session.id}`;
      process.stdout.write(`  session ${session.id}\n  ${consoleUrl}\n`);

      const content = buildUserMessageContent(task.prompt, task.attachImage ? image : undefined);
      const { events, capped, timedOut } = await driveSession(client, session.id, content, cli);
      const transcript = reduceEvents(events as Parameters<typeof reduceEvents>[0]);
      const result = evaluateTask(transcript, task);

      const savedAssets = saveAssets(outDir, task, transcript);
      writeArtifact(outDir, task, transcript, result, savedAssets, { capped, timedOut, sessionId: session.id, consoleUrl });

      const derivedPrompt = firstDerivedPrompt(transcript, task);
      runResults.push({
        taskId: task.id,
        sessionId: session.id,
        consoleUrl,
        capped,
        timedOut,
        result,
        derivedPrompt,
        finalTextPreview: preview(transcript.finalText),
        savedAssets,
      });
      printTaskOutcome(transcript, result, { capped, timedOut, derivedPrompt, savedAssets });
    } catch (err) {
      const msg = describeError(err);
      process.stdout.write(`  ERROR: ${msg}\n`);
      runResults.push({
        taskId: task.id,
        sessionId: '(none)',
        consoleUrl: '',
        capped: false,
        timedOut: false,
        result: { taskId: task.id, criteria: [], pass: false },
        finalTextPreview: '',
        savedAssets: [],
        error: msg,
      });
    }
    process.stdout.write('\n');
  }

  const summary = {
    test: 'test4',
    stage: cli.stage,
    when: new Date().toISOString(),
    agentId: cli.agentId,
    vaultId: cli.vaultId,
    environmentId,
    outDir,
    tasks: runResults.map((r) => ({
      taskId: r.taskId,
      sessionId: r.sessionId,
      pass: r.result.pass,
      capped: r.capped,
      timedOut: r.timedOut,
      criteria: r.result.criteria,
      savedAssets: r.savedAssets,
      error: r.error,
    })),
  };
  writeFileSync(resolve(outDir, 'summary.json'), `${JSON.stringify(summary, null, 2)}\n`);
  printGate(runResults, outDir);
}

// Drive one session: open stream first, send the user turn, drain to a terminal
// stop with bounded tool-call and wall-clock caps. Returns the collected events.
async function driveSession(
  client: import('@anthropic-ai/sdk').default,
  sessionId: string,
  content: ReturnType<typeof buildUserMessageContent>,
  cli: Cli,
): Promise<{ events: unknown[]; capped: boolean; timedOut: boolean }> {
  const ac = new AbortController();
  const timer = setTimeout(() => ac.abort(), cli.taskTimeoutMs);
  const events: unknown[] = [];
  let toolUses = 0;
  let capped = false;
  let timedOut = false;
  try {
    const stream = await client.beta.sessions.events.stream(sessionId, undefined, { signal: ac.signal });
    await client.beta.sessions.events.send(sessionId, {
      events: [{ type: 'user.message', content }],
    });
    for await (const ev of stream) {
      events.push(ev);
      const type = (ev as { type?: string }).type;
      if (type === 'agent.mcp_tool_use') {
        toolUses++;
        if (toolUses > cli.maxToolCalls) {
          capped = true;
          await safeInterrupt(client, sessionId);
          break;
        }
      } else if (type === 'session.status_idle') {
        const stop = (ev as { stop_reason?: { type?: string; event_ids?: string[] } }).stop_reason;
        if (stop?.type === 'requires_action') {
          // Auto-allow pending tool confirmations (we explicitly want the agent to
          // call the limner pipelines), bounded by the tool-call cap.
          const ids = stop.event_ids ?? [];
          if (toolUses <= cli.maxToolCalls && ids.length > 0) {
            await client.beta.sessions.events.send(sessionId, {
              events: ids.map((id) => ({ type: 'user.tool_confirmation' as const, tool_use_id: id, result: 'allow' as const })),
            });
            continue;
          }
          capped = true;
          await safeInterrupt(client, sessionId);
          break;
        }
        break; // end_turn or retries_exhausted — terminal
      } else if (type === 'session.status_terminated') {
        break;
      }
    }
  } catch (err) {
    if (ac.signal.aborted) {
      timedOut = true;
      await safeInterrupt(client, sessionId);
    } else {
      throw err;
    }
  } finally {
    clearTimeout(timer);
  }
  return { events, capped, timedOut };
}

async function safeInterrupt(
  client: import('@anthropic-ai/sdk').default,
  sessionId: string,
): Promise<void> {
  try {
    await client.beta.sessions.events.send(sessionId, { events: [{ type: 'user.interrupt' }] });
  } catch {
    // best-effort
  }
}

function firstDerivedPrompt(transcript: TaskTranscript, task: TaskSpec): string | undefined {
  const want = task.expectedTool ? normalizeToolName(task.expectedTool) : undefined;
  const call = transcript.toolCalls.find(
    (c) => !want || normalizeToolName(c.name) === want,
  );
  const input = call?.input as { prompt?: unknown } | undefined;
  return typeof input?.prompt === 'string' ? input.prompt : undefined;
}

function saveAssets(outDir: string, task: TaskSpec, transcript: TaskTranscript): string[] {
  const saved: string[] = [];
  let n = 0;
  for (const call of transcript.toolCalls) {
    for (const asset of call.assets) {
      if (asset.kind !== 'image') continue;
      n += 1;
      const filename = `${task.id}-${shortToolName(call.name)}-${n}.${asset.ext}`;
      writeFileSync(resolve(outDir, filename), Buffer.from(asset.base64, 'base64'));
      saved.push(filename);
    }
  }
  return saved;
}

// Write the per-task transcript artifact. Base64 image bytes are NEVER included:
// assets are summarized (count + saved filename), and the source photo (which
// only ever appears in the SENT user turn, not received events) is not present.
function writeArtifact(
  outDir: string,
  task: TaskSpec,
  transcript: TaskTranscript,
  result: TaskResult,
  savedAssets: string[],
  meta: { capped: boolean; timedOut: boolean; sessionId: string; consoleUrl: string },
): void {
  let assetIdx = 0;
  const toolCalls = transcript.toolCalls.map((c) => ({
    name: c.name,
    mcpServerName: c.mcpServerName,
    input: c.input,
    isError: c.isError,
    assets: c.assets.map((a) =>
      summarizeAssetForArtifact(a, a.kind === 'image' ? savedAssets[assetIdx++] : undefined),
    ),
  }));
  const artifact = {
    taskId: task.id,
    stage: task.stage,
    kind: task.kind,
    expectedTool: task.expectedTool,
    sessionId: meta.sessionId,
    consoleUrl: meta.consoleUrl,
    promptSent: task.prompt,
    capped: meta.capped,
    timedOut: meta.timedOut,
    transcript: {
      thinkingCount: transcript.thinkingCount,
      modelRequests: transcript.modelRequests,
      idleStopReason: transcript.idleStopReason,
      terminated: transcript.terminated,
      toolCalls,
      finalText: transcript.finalText,
      errors: transcript.errors,
    },
    evaluation: result,
  };
  writeFileSync(resolve(outDir, `${task.id}.transcript.json`), `${JSON.stringify(artifact, null, 2)}\n`);
}

function printTaskOutcome(
  transcript: TaskTranscript,
  result: TaskResult,
  extra: { capped: boolean; timedOut: boolean; derivedPrompt?: string; savedAssets: string[] },
): void {
  const verdict = result.pass ? 'PASS' : 'FAIL';
  process.stdout.write(`  ${verdict}${extra.capped ? ' (capped)' : ''}${extra.timedOut ? ' (timed out)' : ''}\n`);
  for (const c of result.criteria) {
    process.stdout.write(`    ${c.pass ? '✓' : '✗'} ${c.name}: ${c.detail}\n`);
  }
  if (extra.derivedPrompt) process.stdout.write(`    derived prompt: ${preview(extra.derivedPrompt, 300)}\n`);
  if (extra.savedAssets.length) process.stdout.write(`    saved: ${extra.savedAssets.join(', ')}\n`);
  for (const e of transcript.errors) {
    process.stdout.write(`    ⚠ session.error [${e.type}] ${e.message}${e.isMaskedModelRequestFailure ? '  <-- MASKED model_request_failed_error' : ''}\n`);
  }
}

function printGate(results: readonly TaskRunResult[], outDir: string): void {
  const anyMasked = results.some((r) =>
    r.result.criteria.some((c) => c.name === 'schemasAccepted' && !c.pass),
  );
  const reachedMcp = results.some((r) =>
    r.result.criteria.some((c) => c.name === 'mcpToolsReached' && c.pass),
  );
  const visionUsed = results.some((r) =>
    r.result.criteria.some((c) => c.name === 'visionDerivedPrompt' && c.pass),
  );
  const skillUsed = results.some((r) =>
    r.result.criteria.some((c) => c.name === 'fileTypesSkillUsed' && c.pass),
  );
  process.stdout.write('— Test 4 gate —\n');
  process.stdout.write(`  schemas accepted (no masked error): ${anyMasked ? 'NO ✗' : 'YES ✓'}\n`);
  process.stdout.write(`  MCP tools reached (vault auth):     ${reachedMcp ? 'YES ✓' : 'no ✗'}\n`);
  process.stdout.write(`  vision used (derived prompt):       ${visionUsed ? 'YES ✓' : 'no ✗'}\n`);
  process.stdout.write(`  file-types skill used:              ${skillUsed ? 'YES ✓' : 'n/a'}\n`);
  const passed = results.filter((r) => r.result.pass).length;
  process.stdout.write(`  tasks passed: ${passed}/${results.length}\n`);
  process.stdout.write(`\nArtifacts + summary → ${outDir}\n`);
}

function describeError(err: unknown): string {
  if (err && typeof err === 'object') {
    const e = err as { status?: number; error?: { type?: string; message?: string }; message?: string; request_id?: string };
    const parts = [
      e.status ? `HTTP ${e.status}` : undefined,
      e.error?.type,
      e.error?.message ?? e.message,
      e.request_id ? `request_id=${e.request_id}` : undefined,
    ].filter(Boolean);
    if (parts.length) return parts.join(' · ');
  }
  return err instanceof Error ? err.message : String(err);
}

main().catch((err: unknown) => {
  process.stderr.write(`test-agent: ${describeError(err)}\n`);
  process.exit(1);
});
