#!/usr/bin/env node
// Single-source version stamper (A7).
//
// The root package.json `version` is the ONE source of truth. This script
// regenerates every derived version site from it:
//   - packages/limner-mcp/src/version.ts        (generated TS constant)
//   - packages/limner-cma-tools/src/version.ts  (generated TS constant)
//   - packages/limner-mcp/manifest.json         (.version)
//   - packages/{limner-core,limner-mcp,limner-cma-tools}/package.json (.version)
//
// Bump the version in ONE place (root package.json), then run
// `pnpm sync-version`. CI runs this and fails if anything drifted (i.e. the
// root version was bumped without re-syncing) — see .github/workflows/ci.yml.
//
// JSON files are edited with a targeted string replace (not re-serialized) so
// only the version line changes and the rest of the formatting is preserved.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const abs = (rel) => join(repoRoot, rel);

const rootPkg = JSON.parse(readFileSync(abs('package.json'), 'utf8'));
const version = rootPkg.version;
if (typeof version !== 'string' || version.length === 0) {
  throw new Error('root package.json has no usable "version"');
}

let changed = 0;
function write(rel, next) {
  const path = abs(rel);
  let current = '';
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    /* file does not exist yet */
  }
  if (current !== next) {
    writeFileSync(path, next);
    changed++;
    console.log(`  synced ${rel}`);
  }
}

// 1. Generated TS constants consumed by the server-version strings.
const versionTs =
  '// GENERATED by scripts/sync-version.mjs — do not edit by hand.\n' +
  '// Run `pnpm sync-version` after bumping the root package.json version.\n' +
  `export const VERSION = '${version}' as const;\n`;
write('packages/limner-mcp/src/version.ts', versionTs);
write('packages/limner-cma-tools/src/version.ts', versionTs);

// 2. The first `"version": "..."` in each JSON file (the top-level version).
const VERSION_RE = /("version"\s*:\s*)"[^"]*"/;
for (const rel of [
  'packages/limner-core/package.json',
  'packages/limner-mcp/package.json',
  'packages/limner-cma-tools/package.json',
  'packages/limner-mcp/manifest.json',
]) {
  const text = readFileSync(abs(rel), 'utf8');
  if (!VERSION_RE.test(text)) {
    throw new Error(`no "version" field found in ${rel}`);
  }
  write(rel, text.replace(VERSION_RE, `$1"${version}"`));
}

console.log(
  changed === 0
    ? `version already in sync @ ${version}`
    : `version sync complete @ ${version} (${changed} file(s) updated)`,
);
